### ISSUE TITLE
Wrong 2.5 download link

### ISSUE THREAD

**Issue by cicku** [ldoolitt/vhd2vl#1]
http://doolittle.icarus.com/~larry/vhd2vl/

I still see [2.4 link](http://doolittle.icarus.com/~larry/vhd2vl/vhd2vl-2.4.tar.gz) of 2.5 release.

Please fix.

**Comment by ldoolitt** [comment]
Christopher -

On Wed, Oct 07, 2015 at 04:47:39PM -0700, Christopher Meng wrote:
> http://doolittle.icarus.com/~larry/vhd2vl/
> I still see [2.4 link](http://doolittle.icarus.com/~larry/vhd2vl/vhd2vl-2.4.tar.gz) of 2.5 release

Fixed.  Thanks for pointing this out!

  - Larry
