### ISSUE TITLE
Undefined behaviour bugs

### ISSUE THREAD

**Issue by acairncross** [ldoolitt/vhd2vl#18]
There are a number of bugs that you can uncover by compiling with ASan (`-fsanitize=address`) and MSan (`-fsanitize=memory` with clang).

One of them, from ASan, has an easy fix here: https://github.com/acairncross/vhd2vl/commit/f0e1d1eb2fb88eff37d53ac59d7a61b8413834b4

The others, from MSan, are a bit more involved, but are generally the result of reading fields that aren't always initialized like the `op` field of `expdata`. I couldn't figure out exactly what the `op` field is supposed to contain so haven't got a patch for it.

I think these are the cause of #17 and #15, i.e. `vhd2vl` has non-deterministic output, although I've only seen the non-determinism appear if you compile with `-D_FORTIFY_SOURCE=1` (or `2`)

**Comment by ldoolitt** [comment]
I'm not skilled with clang ASan or Msan, but I confirm the correctness of your patch f9e1d1e.  Applied to master.  Thanks!
I can take a quick look around at the `op` field, but won't promise any results.

**Comment by ldoolitt** [comment]
Please re-test with new commit 869d4429 "Avoid using uninitialized op".
It's possible I missed a few cases.  I tried really hard to not add regressions.

Thanks for the bug report; this looks like an improvement!

**Comment by acairncross** [comment]
That works reliably for me too, thanks!

There's one more uninitialized field flagged up by MSan, see here for a patch https://github.com/acairncross/vhd2vl/commit/0b0a036646f57be5feba06c065a87bdb4e686f76 - haven't seen any bugs triggered by it yet, but would be good to fix.

**Comment by ldoolitt** [comment]
I applied 0b0a03664 to master.  Thanks!  I think that makes it correct to close this issue.
